### ISSUE TITLE
C++17 does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by GeneralAccess** [aforsythe/IlmBase#1]
I have a Flatpak with ilmbase as a dependency. It used to work, with some warnings:

```
/app/include/OpenEXR/ImathMatrix.h:2814:36: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 2814 | Matrix44<T>::invert (bool singExc) throw (IEX_NAMESPACE::MathExc)
```
Since the platform has changed I get errors:
`_ImathMatrix.h:275:25: error: ISO C++17 does not allow dynamic exception specifications_
`
I don't use C++, but I am guessing that something that was deprecated in C++11 causes an error in C++ 17. Any idea how I might overcome this?

**Comment by kermitdafrog8** [comment]
I am also getting this error as well when trying to build with bootstrap and configure on Slackware.

**Comment by GeneralAccess** [comment]
My original post is from 2021 so rather out-of-date now. I have successfully built the Flatpak several times since, the latest was about 6 months ago, using this module:

```
  - name: ilmbase
    build-options:
      cxxflags: -std=c++14
    config-opts:
      - --disable-static
    sources:
      - type: archive
        url: https://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz
        sha256: cac206e63be68136ef556c2b555df659f45098c159ce24804e9d5e9e0286609e
```
